### ISSUE TITLE
git 目录下执行 git rm -rf .idea 才能把.idea 忽略掉

### ISSUE THREAD

**Issue by yingchaoyong** [857681664/biyesheji#1]

**Comment by 857681664** [comment]
这样啊，之前一直没用，后来我装了gitignore插件，可以鼠标右键直接加入忽略，推荐一发

**Comment by yingchaoyong** [comment]
没，你在没有新建.gitignore的时候，把.idea添加到了git的workspace里面，然后提交了，后面再忽略它还是会被记录，要把它从git的work tree移除掉

**Comment by 857681664** [comment]
我执行过git rm，貌似直接把这个文件夹从我硬盘上删掉了，后来又重新生成了，然后我加到gitignore后就可以正常忽略了

**Comment by yingchaoyong** [comment]
git rm 不会删除实际文件

**Comment by 857681664** [comment]
难道我那里出了bug

**Comment by yingchaoyong** [comment]
记错，git rm也会删掉目录下的文件

**Comment by yingchaoyong** [comment]
应该用reset（逃

**Comment by 857681664** [comment]
滑稽
